// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbL68aFkTpfRfW20tOcnB2QkfDtiSYsUM',
    appId: '1:956994840327:web:3b13baf8bd77713a79c7a2',
    messagingSenderId: '956994840327',
    projectId: 'taskmanager-b8d98',
    authDomain: 'taskmanager-b8d98.firebaseapp.com',
    storageBucket: 'taskmanager-b8d98.firebasestorage.app',
    measurementId: 'G-HL2W5BQSLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNd6Fj8L9Tdn8PmCVFL8QKhNkUQo-_eg4',
    appId: '1:956994840327:android:5ba67822bcd70ff879c7a2',
    messagingSenderId: '956994840327',
    projectId: 'taskmanager-b8d98',
    storageBucket: 'taskmanager-b8d98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeCmTDmv-00TPxqRdcCga73w5eyQ4yc_A',
    appId: '1:956994840327:ios:d39fb8cd942de69079c7a2',
    messagingSenderId: '956994840327',
    projectId: 'taskmanager-b8d98',
    storageBucket: 'taskmanager-b8d98.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );
}
